[
  {
    "number": 0,
    "route": "GEO",
    "destZ": "暫停服務",
    "destY": "暫停服務",
    "maxPZ": "1",
    "priceZ1": "0.0",
    "halfpriceZ1": "0.0",
    "maxPY": "1",
    "priceY1": "0.0",
    "halfpriceY1": "0.0"
  },
  {
    "number": 1,
    "route": "23",
    "destZ": "豬怕邨",
    "destY": "大新碼頭",
    "maxPZ": "1",
    "priceZ1": "4.1",
    "halfpriceZ1": "2.1",
    "maxPY": "1",
    "priceY1": "4.1",
    "halfpriceY1": "2.1"
  },
  {
    "number": 2,
    "route": "24",
    "destZ": "沙善邨",
    "destY": "大新中心",
    "maxPZ": "1",
    "priceZ1": "4.1",
    "halfpriceZ1": "2.1",
    "maxPY": "1",
    "priceY1": "4.1",
    "halfpriceY1": "2.1"
  },
  {
    "number": 3,
    "route": "73",
    "destZ": "甘泉市中心",
    "destY": "海興村",
    "maxPZ": "4",
    "priceZ1": "11.0",
    "halfpriceZ1": "5.5",
    "priceZ2": "8.9",
    "halfpriceZ2": "4.5",
    "priceZ3": "6.8",
    "halfpriceZ3": "3.4",
    "priceZ4": "4.3",
    "halfpriceZ4": "2.2",
    "maxPY": "4",
    "priceY1": "11.0",
    "halfpriceY1": "5.5",
    "priceY2": "8.9",
    "halfpriceY2": "4.5",
    "priceY3": "6.8",
    "halfpriceY3": "3.4",
    "priceY4": "5.8",
    "halfpriceY4": "2.9"
  },
  {
    "number": 4,
    "route": "23M",
    "destZ": "豬怕邨",
    "destY": "馬奶邨",
    "maxPZ": "1",
    "priceZ1": "4.1",
    "halfpriceZ1": "2.1",
    "maxPY": "1",
    "priceY1": "4.1",
    "halfpriceY1": "2.1"
  },
  {
    "number": 5,
    "route": "24D",
    "destZ": "沙善邨",
    "destY": "豬怕學校村",
    "maxPZ": "1",
    "priceZ1": "3.8",
    "halfpriceZ1": "1.9",
    "maxPY": "1",
    "priceY1": "3.8",
    "halfpriceY1": "1.9"
  },
  {
    "number": 6,
    "route": "24H",
    "destZ": "沙善邨",
    "destY": "豬怕市中心",
    "maxPZ": "1",
    "priceZ1": "4.1",
    "halfpriceZ1": "2.1",
    "maxPY": "1",
    "priceY1": "4.1",
    "halfpriceY1": "2.1"
  },
  {
    "number": 7,
    "route": "41A",
    "destZ": "甘怡站",
    "destY": "甘泉市中心",
    "maxPZ": "1",
    "priceZ1": "4.6",
    "halfpriceZ1": "2.3",
    "maxPY": "1",
    "priceY1": "4.6",
    "halfpriceY1": "2.3"
  },
  {
    "number": 8,
    "route": "41M",
    "destZ": "甘怡站",
    "destY": "松蔭邨",
    "maxPZ": "1",
    "priceZ1": "4.6",
    "halfpriceZ1": "2.3",
    "maxPY": "1",
    "priceY1": "4.6",
    "halfpriceY1": "2.3"
  },
  {
    "number": 9,
    "route": "41X",
    "destZ": "甘泉市中心",
    "destY": "松蔭邨",
    "maxPZ": "1",
    "priceZ1": "5.2",
    "halfpriceZ1": "2.6",
    "maxPY": "1",
    "priceY1": "5.2",
    "halfpriceY1": "2.6"
  },
  {
    "number": 10,
    "route": "42M",
    "destZ": "甘怡站",
    "destY": "基達(南)",
    "maxPZ": "1",
    "priceZ1": "5.8",
    "halfpriceZ1": "2.9",
    "maxPY": "1",
    "priceY1": "5.8",
    "halfpriceY1": "2.9"
  },
  {
    "number": 11,
    "route": "73A",
    "destZ": "大新碼頭",
    "destY": "海信圍村",
    "maxPZ": "2",
    "priceZ1": "7.5",
    "halfpriceZ1": "3.8",
    "priceZ2": "5.8",
    "halfpriceZ2": "2.9",
    "maxPY": "2",
    "priceY1": "7.5",
    "halfpriceY1": "3.8",
    "priceY2": "5.8",
    "halfpriceY2": "2.9"
  },
  {
    "number": 12,
    "route": "73R",
    "destZ": "甘泉市中心",
    "destY": "七葉鎮",
    "maxPZ": "1",
    "priceZ1": "12.6",
    "halfpriceZ1": "6.3",
    "maxPY": "1",
    "priceY1": "12.6",
    "halfpriceY1": "6.3"
  },
  {
    "number": 13,
    "route": "N23",
    "destZ": "豬怕邨",
    "destY": "沙善邨",
    "maxPZ": "1",
    "priceZ1": "5.4",
    "halfpriceZ1": "2.7",
    "maxPY": "1",
    "priceY1": "5.4",
    "halfpriceY1": "2.7"
  },
  {
    "number": 14,
    "route": "273P",
    "destZ": "甘泉工業區",
    "destY": "豬怕(南)",
    "maxPZ": "1",
    "priceZ1": "7.8",
    "halfpriceZ1": "3.9",
    "maxPY": "1",
    "priceY1": "7.8",
    "halfpriceY1": "3.9"
  },
  {
    "number": 15,
    "route": "273X",
    "destZ": "甘泉市中心",
    "destY": "豬怕邨",
    "maxPZ": "2",
    "priceZ1": "8.9",
    "halfpriceZ1": "4.5",
    "priceZ2": "4.6",
    "halfpriceZ2": "2.3",
    "maxPY": "2",
    "priceY1": "8.9",
    "halfpriceY1": "4.5",
    "priceY2": "4.1",
    "halfpriceY2": "2.1"
  },
  {
    "number": 16,
    "route": "274M",
    "destZ": "甘怡站",
    "destY": "沙善邨",
    "maxPZ": "2",
    "priceZ1": "7.5",
    "halfpriceZ1": "3.8",
    "priceZ2": "4.6",
    "halfpriceZ2": "2.3",
    "maxPY": "2",
    "priceY1": "7.5",
    "halfpriceY1": "3.8",
    "priceY2": "4.1",
    "halfpriceY2": "2.1"
  },
  {
    "number": 17,
    "route": "275A",
    "destZ": "甘泉工業區",
    "destY": "豬怕(西)",
    "maxPZ": "2",
    "priceZ1": "7.5",
    "halfpriceZ1": "3.8",
    "priceZ2": "4.6",
    "halfpriceZ2": "2.3",
    "maxPY": "2",
    "priceY1": "7.5",
    "halfpriceY1": "3.8",
    "priceY2": "4.1",
    "halfpriceY2": "2.1"
  },
  {
    "number": 18,
    "route": "275X",
    "destZ": "甘泉市中心",
    "destY": "大新碼頭",
    "maxPZ": "2",
    "priceZ1": "8.9",
    "halfpriceZ1": "4.5",
    "priceZ2": "4.6",
    "halfpriceZ2": "2.3",
    "maxPY": "2",
    "priceY1": "8.9",
    "halfpriceY1": "4.5",
    "priceY2": "4.1",
    "halfpriceY2": "2.1"
  },
  {
    "number": 19,
    "route": "N247",
    "destZ": "甘泉市中心",
    "destY": "大新中心",
    "maxPZ": "2",
    "priceZ1": "11.6",
    "halfpriceZ1": "5.8",
    "priceZ2": "5.3",
    "halfpriceZ2": "2.7",
    "maxPY": "2",
    "priceY1": "11.6",
    "halfpriceY1": "5.8",
    "priceY2": "5.3",
    "halfpriceY2": "2.7"
  }
]
